return {
	aur = {
		{ name = "7zip", desc = "File archiver with a high compression ratio" },
		{ name = "asciinema", desc = "Records and shares terminal sessions", config = "asciinema" },
		{ name = "base", desc = "Minimal package set for a base Arch installation" },
		{ name = "adw-gtk-theme", desc = "gtk theme needed for noctalia templates" },
		{ name = "base-devel", desc = "Tools needed to build Arch packages (makepkg, etc.)" },
		{ name = "bat", desc = "cat, but with wings" },
		{ name = "biber", desc = "A bibliography management tool for LaTeX" },
		{ name = "bluez", desc = "bluetooth package for arch", system_service = "bluetooth.service" },
		{ name = "bluez-utils", desc = "provides bluetoothctl utility" },
		{ name = "btop", desc = "Resource monitor (fancy top/htop alternative)", config = "btop" },
		{ name = "btrfs-progs", desc = "btrfs filesystem utilities" },
		{ name = "calibre-bin", desc = "E-book management application (precompiled binary)" },
		{ name = "cliphist", desc = "Wayland clipboard history manager" },
		{ name = "cloudflare-warp-bin", desc = "Cloudflare Warp Client", system_service = "warp-svc.service" },
		{ name = "cmatrix", desc = "matrix animation in terminal" },
		{ name = "diff-so-fancy", desc = "Makes git/diff output more human friendly" },
		{ name = "thunar", desc = "A GUI file manager" },
		{ name = "dosfstools", desc = "Utilities for creating and checking FAT/VFAT filesystems" },
		{ name = "downgrade", desc = "Bash script to downgrade packages" },
		{ name = "efibootmgr", desc = "Utility to modify the UEFI Boot Manager" },
		{ name = "entr", desc = "A utility that runs arbitrary commands when files change" },
		{ name = "exfatprogs", desc = "exFAT filesystem userspace utilities for the Linux Kernel exfat drive" },
		{ name = "eza", desc = "ls replacement on fire", config = "eza" },
		{ name = "fastfetch", desc = "Fast, highly customizable system info tool" },
		{ name = "fd", desc = "A fast find replacement" },
		{ name = "ffmpeg", desc = "Complete solution to record, convert and stream audio and video" },
		{ name = "ffmpegthumbnailer", desc = "A utility to produce video thumbnails for yazi" },
		{ name = "firefox", desc = "The main browser", config = "firefox" },
		{ name = "flatpak", desc = "Enables installing flatpaks" },
		{ name = "freecad", desc = "Parametric 3D CAD modeler", config = "freecad" },
		{ name = "fzf", desc = "Fuzzy finder" },
		{ name = "gaupol", desc = "A tool to manipulate srt files" },
		{ name = "git", desc = "A neat version control system", config = "git" },
		{ name = "git-delta", desc = "Syntax-highlighting pager for git and diff output" },
		{ name = "github-cli", desc = "GitHub's official command-line tool", config = "gh" },
		{ name = "gnome-disk-utility", desc = "As the name says" },
		{
			name = "gnome-keyring",
			desc = "Stores passwords, keys, and certificates securely",
			user_service = "gnome-keyring-daemon.service",
		},
		{
			name = "greetd",
			desc = "A simple customizable login manager",
			system_service = "greetd.service",
			root_config = { { source = "greetd/config.toml", target = "/etc/greetd/config.toml" } },
		},
		{
			name = "grub",
			desc = "bootloader",
			post_install = "sudo sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/g' /etc/default/grub; sudo grub-mkconfig -o /boot/grub/grub.cfg",
		},

		{
			name = "grub-btrfs",
			desc = "Include btrfs snapshots in GRUB boot options",
			user_service = "grub-btrfsd.service",
		},
		{ name = "gvfs", desc = "filesystem management utility for thunar" },
		{ name = "gwenview", desc = "Image viewing utility by KDE" },
		{ name = "handlr-regex", desc = "Powerful alternative to xdg-utils written in Rust" },
		{ name = "httrack", desc = "Download entire websites" },
		{ name = "hugo", desc = "Fast and modern static site generator" },
		{ name = "hyprland", desc = "A dynamic tiling Wayland compositor", config = "hypr" },
		{ name = "imagemagick", desc = "An image viewing/manipulation program" },
		{ name = "intel-media-driver", desc = "As the name says..." },
		{
			name = "intel-media-sdk",
			desc = "Legacy API for hardware video acceleration on Intel GPUs (Broadwell to Rocket Lake)",
		},
		{ name = "intel-ucode", desc = "Microcode update files for Intel CPUs" },
		{ name = "jq", desc = "A commandline JSON parser" },
		{ name = "keepassxc-git", desc = "Cross-platform password manager", config = "keepassxc" },
		{ name = "kitty", desc = "A fast, feature-rich, GPU based terminal emulator", config = "kitty" },
		{ name = "lazygit", desc = "A tui interface for git", config = "lazygit" },
		{ name = "libva-intel-driver", desc = "VA-API implementation for Intel G45 and HD Graphics family" },
		{ name = "linux-firmware", desc = "as the name says" },
		{ name = "lua", desc = "A fast programming language designed for extensibility of other applications" },
		{ name = "man-db", desc = "A utility to read man pages" },
		{ name = "mediainfo", desc = "Displays technical info about media files" },
		{ name = "mkvtoolnix-cli", desc = "A tool to manipulate mkv files" },
		{
			name = "mpd",
			desc = "Flexible, powerful, server-side application for playing music",
			user_service = "mpd.service",
		},
		{ name = "mpv", desc = "The OG video player", config = "mpv" },
		{ name = "neovide", desc = "A graphical interface for neovim" },
		{ name = "neovim", desc = "A powerful text editor", config = "nvim" },
		{ name = "ttf-hack-nerd", desc = "hack nerd font" },
		{ name = "network-manager-applet", desc = "System tray applet for NetworkManager" },
		{
			name = "networkmanager",
			desc = "Network connection manager and user applications",
			system_service = "NetworkManager.service",
		},
		{
			name = "noctalia-git",
			desc = "Minimal Wayland desktop shell built on Quickshell (git version)",
			config = "noctalia",
		},
		{
			name = "noctalia-greeter",
			desc = "noctalia theme for greetd",
			root_config = {
				{
					source = "noctalia-greeter/greeter.toml",
					target = "/var/lib/noctalia-greeter/greeter.toml",
				},
			},
		},
		{ name = "ttf-noto-nerd", desc = "google noto fonts ttf with nerd-fonts patch" },
		{ name = "npm", desc = "Package manager for Node.js" },
		{ name = "ntfs-3g", desc = "NTFS filesystem driver and utilities" },
		{ name = "nwg-look", desc = "utility to style gtk applications, needed for noctalia gtk template" },
		{ name = "obsidian", desc = "A neat markdown utility" },
		{
			name = "pacman",
			desc = "arch package manager",
			root_config = { { source = "pacman/pacman.conf", target = "/etc/pacman.conf" } },
		},
		{ name = "pandoc-bin", desc = "A document converter tool" },
		{ name = "pavucontrol", desc = "pulseaudio volume control" },
		{
			name = "pipewire",
			desc = "Low-latency audio/video router and processor",
			user_service = "pipewire.service",
		},
		{ name = "pipewire-alsa", desc = "Low-latency audio/video router and processor - ALSA configuration" },
		{
			name = "pipewire-pulse",
			desc = "Low-latency audio/video router and processor - PulseAudio replacement",
			user_service = "pipewire-pulse.service",
		},
		{ name = "pdfjs", desc = "A utility required to natively view pdfs on browsers" },
		{ name = "pdftk", desc = "Command-line tool for working with PDFs" },
		{ name = "poppler", desc = "PDF rendering library based on xpdf 3.0" },
		{ name = "python-pip", desc = "A tool for installing python packages" },
		{ name = "qbittorrent", desc = "An open source torrent client" },
		{ name = "qpdf", desc = "A Content-Preserving PDF Transformation System" },
		{ name = "qpwgraph", desc = "Graphical patchbay for PipeWire" },
		{
			name = "reflector",
			desc = "A Python 3 module and script to retrieve and filter the latest Pacman mirror list",
			system_service = "reflector.service",
			post_install = "sudo reflector --latest 10 --country US --age 24 --protocol http,https --sort rate --download-timeout 60 --save /etc/pacman.d/mirrorlist",
		},
		{ name = "qt6-wayland", desc = "provides qt6 api for wayland" },
		{ name = "qt6ct-kde", desc = "qt6 configuration utility" },
		{ name = "ripgrep", desc = "A search tool that combines the usability of ag with the raw speed of grep" },
		{ name = "rmpc", desc = "A beautiful and configurable TUI client for MPD" },
		{
			name = "sioyek-dev",
			desc = "PDF viewer for research papers and technical books with vim keybinds.",
			config = "sioyek",
		},
		{ name = "starship", desc = "A cross platform prompt for various shells", config = "starship" },
		{ name = "steam", desc = "Valve's digital distribution platform for games" },
		{ name = "stow", desc = "A powerful symlink utility" },
		{
			name = "syncthing",
			desc = "Sync files across devices",
			user_service = "syncthing.service",
		},
		{ name = "texlive-basic", desc = "LaTeX" },
		{ name = "texlive-bibtexextra", desc = "LaTeX" },
		{ name = "texlive-binextra", desc = "LaTeX" },
		{ name = "texlive-fontsrecommended", desc = "LaTeX" },
		{ name = "texlive-langenglish", desc = "LaTeX" },
		{ name = "texlive-latex", desc = "LaTeX" },
		{ name = "texlive-latexextra", desc = "LaTeX" },
		{ name = "texlive-latexrecommended", desc = "LaTeX" },
		{ name = "texlive-mathscience", desc = "LaTeX" },
		{ name = "texlive-pictures", desc = "LaTeX" },
		{ name = "texlive-plaingeneric", desc = "LaTeX" },
		{ name = "texlive-publishers", desc = "LaTeX" },
		{ name = "tlrc", desc = "A tool that gives easy to understand versions of the manual with example" },
		{ name = "tmate", desc = "Utility to access remote terminal" },
		{ name = "tmux", desc = "Terminal multiplexer", config = "tmux" },
		{
			name = "topgrade",
			desc = "A tool written in rust to update packages across several package managers",
			config = "topgrade",
		},
		{ name = "trash-cli", desc = "A cli trash manager" },
		{ name = "tree-sitter-cli", desc = "CLI tool for developing, testing, and using Tree-sitter parsers" },
		{ name = "ttf-kannada-font", desc = "Kannada font" },
		{ name = "adobe-source-sans-fonts", desc = "Sans-serif font family for user interface environments" },
		{ name = "adobe-source-serif-fonts", desc = "Serif typeface designed to complement Source Sans" },
		{ name = "resvg", desc = "tool needed for svg previews in yazi" },
		{
			name = "systemd",
			desc = "system and service manager",
			root_config = { { source = "systemd/power.conf", target = "/etc/systemd/logind.conf.d/power.conf" } },
		},
		{
			name = "snapper",
			desc = "Utility for managing filesystem snapshots",
			root_config = {
				{
					source = "snapper/root",
					target = "/etc/snapper/configs/root",
				},
				{
					source = "snapper/snapper-conf",
					target = "/etc/conf.d/snapper",
				},
			},
			system_service = "snapper-cleanup.timer",
			post_install = "if ! sudo btrfs subvolume show /.snapshots >/dev/null 2>&1; then sudo rm -rf /.snapshots && sudo btrfs subvolume create /.snapshots; fi && [ -f /etc/snapper/configs/root ] || sudo snapper -c root create-config /",
		},
		{
			name = "snap-pac",
			desc = "Pacman hooks for automatically taking snapper snapshots before and after updates",
		},
		{ name = "tumbler", desc = "A utility to generate thumbnails" },
		{ name = "typst", desc = "Markup-based typesetting system, a modern LaTeX alternative" },
		{ name = "udiskie", desc = "Automounter for removable media using udisks" },
		{ name = "unarchiver", desc = "Required for archive preview in yazi" },
		{ name = "visual-studio-code-bin", desc = "Microsoft's code editor (official binary build)", config = "code" },
		{ name = "wget", desc = "A file downloading utility" },
		{ name = "wl-clip-persist", desc = "Keeps Wayland clipboard content after the source app closes" },
		{ name = "wl-clipboard", desc = "Clipboard tool for wayland" },
		{
			name = "xdg-desktop-portal-termfilechooser-hunkyburrito-git",
			desc = "backend to be able to use terminal file managers for browser file selection",
			config = "firefox",
		},
		{ name = "yazi", desc = "A TUI file manager written in rust", config = "yazi" },
		{ name = "yt-dlp", desc = "A youtube-dl fork with additional features and fixes" },
		{ name = "zoxide", desc = "A smarter cd replacement" },
		{ name = "zsh", desc = "An advanced and programmable command interpreter for UNIX", config = "zsh" },
	},

	flatpak = {
		{ name = "com.bambulab.BambuStudio", desc = "Slicer software for Bambu Lab 3D printers", remote = "flathub" },
		{
			name = "com.prusa3d.PrusaSlicer",
			desc = "Slicer software for Prusa (and other) 3D printers",
			remote = "flathub",
		},
		{
			name = "org.bunkus.mkvtoolnix-gui",
			desc = "GUI to create, alter, and inspect Matroska (mkv) files",
			remote = "flathub",
		},
		{ name = "org.gimp.GIMP", desc = "GNU image manipulation program", remote = "flathub" },
		{ name = "org.gimp.GIMP.Plugin.Resynthesizer", desc = "Resynthesizer plugin for gimp", remote = "flathub" },
		{ name = "org.openscad.OpenSCAD", desc = "Script-based parametric 3D CAD modeler", remote = "flathub" },
		{ name = "org.qbittorrent.qBittorrent", desc = "Open source BitTorrent client", remote = "flathub" },
		{ name = "us.zoom.Zoom", desc = "Zoom videoconferencing application", remote = "flathub" },
	},
}
