theme = "tokyo-night"
repeat = "all"
initial_directory = "~/Stuff/Music"
visualizer = "Ascii"
provider = "ytmusic"
eq_preset = "Flat"

[local]
enabled = true
[ytmusic]
enabled = true
client_id = "${YTMUSIC_CLIENT_ID}"
client_secret = "${YTMUSIC_CLIENT_SECRET}"
