theme = "tokyo-night"
repeat = "all"
initial_directory = "~/Stuff/Music"
visualizer = "Ascii"
provider = "local"
eq_preset = "Flat"

shuffle = true
audio_device = bluez_output.C4_A9_B8_4E_94_96.1
[local]
enabled = true
[ytmusic]
enabled = true
client_id = "${YTMUSIC_CLIENT_ID}"
client_secret = "${YTMUSIC_CLIENT_SECRET}"
