[include]
files = ["noctalia.toml"]

[general]
autostart = [
  "noctalia",
  "keepassxc --minimized",
  "udiskie --tray --no-automount",
  "gnome-keyring-daemon",
]
mod_key = "Super"
xwayland = true
show_cheatsheet = true

[events]
lid_close = "noctalia msg session-lock"

[layout.scrolling]
default_extent_fraction = 0.5

[keybinds]
# applications
"Mod+B" = "spawn:firefox"
"Mod+E" = "spawn:kitty -e yazi"
"Mod+N" = "spawn:neovide"
"Mod+P" = "spawn:keepassxc"
"Mod+Return" = "spawn:kitty"
"Mod+S" = "spawn:sioyek --new-window"
"Mod+Shift+E" = "spawn:nemo"
"Mod+Slash" = "cheatsheet-toggle"
"Mod+T" = "spawn:kitty"

# shell
"Mod" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Comma" = "spawn:noctalia msg settings-toggle"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Print" = "spawn:noctalia msg screenshot-region"
"Shift+Print" = "spawn:noctalia msg screenshot-fullscreen"
"XF86AudioMute" = "spawn:noctalia msg volume-mute"
"XF86AudioLowerVolume" = "spawn:noctalia msg volume-down"
"XF86AudioRaiseVolume" = "spawn:noctalia msg volume-up"
"XF86MonBrightnessDown" = "spawn:noctalia msg brightness-down"
"XF86MonBrightnessUp" = "spawn:noctalia msg brightness-up"
"XF86AudioPrev" = "spawn:noctalia msg media previous"
"XF86AudioPlay" = "spawn:noctalia msg media toggle"
"XF86AudioPause" = "spawn:noctalia msg media toggle"
"XF86AudioStop" = "spawn:noctalia msg media stop"
"XF86AudioNext" = "spawn:noctalia msg media next"
# session
"Mod+X" = "spawn:noctalia msg session lock"
"Mod+C" = "spawn:noctalia msg caffeine-toggle"
"XF86PowerOff" = "spawn:noctalia msg panel-toggle session"

# window management
"Mod+Q" = "window-close"
"Alt+F4" = "window-close"
"Alt+Tab" = "spawn:noctalia msg window-switcher"
"F11" = "window-toggle-maximize-to-edges"
"Mod+Shift+F" = "window-toggle-maximize"
"Mod+F" = "window-toggle-floating"
"Mod+Left" = "window-focus-left"
"Mod+H" = "window-focus-left"
"Mod+Shift+Left" = "column-move-left"
"Mod+Shift+H" = "column-move-left"
"Mod+Down" = "window-focus-down"
"Mod+J" = "window-focus-down"
"Mod+Shift+Down" = "window-move-or-workspace-down"
"Mod+Shift+J" = "window-move-or-workspace-down"
"Mod+Up" = "window-focus-up"
"Mod+K" = "window-focus-up"
"Mod+Shift+Up" = "window-move-or-workspace-up"
"Mod+Shift+K" = "window-move-or-workspace-up"
"Mod+Right" = "window-focus-right"
"Mod+L" = "window-focus-right"
"Mod+Shift+Right" = "column-move-right"
"Mod+Shift+L" = "column-move-right"
"Mod+Shift+P" = "window-toggle-pinned"

# workspace
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"
"Mod+Shift+1" = "window-move-to-workspace:1"
"Mod+Shift+2" = "window-move-to-workspace:2"
"Mod+Shift+3" = "window-move-to-workspace:3"
"Mod+Shift+4" = "window-move-to-workspace:4"
"Mod+Shift+5" = "window-move-to-workspace:5"
"Mod+Shift+6" = "window-move-to-workspace:6"
"Mod+Shift+7" = "window-move-to-workspace:7"
"Mod+Shift+8" = "window-move-to-workspace:8"
"Mod+Shift+9" = "window-move-to-workspace:9"

# scratchpad
"Mod+Shift+Space" = "window-move-to-scratchpad"
"Mod+Space" = "scratchpad-toggle"
"Mod+Ctrl+Space" = "window-restore-from-scratchpad"
"Mod+Tab" = "scratchpad-focus-next"

[hot_corners.top_left]
enabled = true
delay_ms = 500
action = "overview-open"

[hot_corners.top_right]
enabled = true
delay_ms = 300
action = "spawn:noctalia msg panel-toggle control-center"

[[window_rule]]
match.app_id = "^dev.noctalia.Noctalia$"
default_floating = true
default_floating_size_px = { width = 1020, height = 900 }

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_floating_size_px = { width = 800, height = 600 }

[[window_rule]]
match.app_id = "^org.keepassxc.KeePassXC$"
default_floating = true
default_floating_size_px = { width = 1020, height = 900 }

[[window_rule]]
match.is_alone = true
default_maximize = true

[input]
[input.keyboard]
options = "caps:escape_shifted_capslock"
[input.touchpad]
natural_scroll = true
[input.cursor]
follows_focus = true
[input.focus]
follows_mouse = true
